<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-aniketiitk25-jpg/blob/main/numpy_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [97]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [98]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [99]:
# Write your code here:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [100]:
# Write your code here:
a = np.full((3, 3), True)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [101]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# Write your code here:
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [103]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# Write your code here:
arr[arr %  2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [105]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
# Write your code here:
new_arr = np.where(arr % 2 != 0, -1, arr)
print(new_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [107]:
# Input — do not modify
arr = np.arange(10)

In [108]:
# Write your code here:
arr = arr.reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [109]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [110]:
# Write your code here:
arr = np.vstack((a, b))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [111]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [112]:
# Write your code here:
arr = np.hstack((a, b))
print(arr)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [113]:
# Input — do not modify
a = np.array([1, 2, 3])

In [114]:
# Write your code here:
pattern = np.hstack((np.repeat(a, 3), np.tile(a, 3)))
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [115]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [116]:
# Write your code here:
common = np.intersect1d(a, b)
print(common)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [117]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [118]:
# Write your code here:
a_new = a[~np.isin(a, b)]
print(a_new)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [119]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [120]:
# Write your code here:
for i in range(10):
    if(a[i] == b[i]):
        print(i)

1
3
5
7


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [121]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [122]:
# Write your code here:
result = a[(a>5) & (a<10)]
print(result)

[6 9]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [123]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [124]:
# Write your code here:
vmaxx = np.vectorize(maxx)
print(vmaxx(a, b))

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [125]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [126]:
# Write your code here:
arr[:, [0,1]] = arr[:, [1,0]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [127]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [128]:
# Write your code here:
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [129]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [130]:
# Write your code here:
arr = arr[::-1]
print(arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [131]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [132]:
# Write your code here:
arr = arr[:, ::-1]
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [133]:
# Write your code here:
arr = np.random.uniform(5,10,(5,3))
print(arr)

[[7.159 9.7   9.088]
 [6.681 5.877 6.864]
 [5.028 6.262 8.978]
 [5.076 7.994 8.019]
 [5.526 6.91  5.182]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [134]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [135]:
# Write your code here:
np.set_printoptions(precision = 3)
print(rand_arr)

[[0.89  0.981 0.06 ]
 [0.891 0.577 0.742]
 [0.63  0.582 0.02 ]
 [0.21  0.545 0.769]
 [0.251 0.286 0.852]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [136]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [137]:
# Write your code here:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [138]:
# Input — do not modify
a = np.arange(15)

In [139]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)


[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [140]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [141]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [142]:
# Write your code here:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris = np.genfromtxt(
    url,
    delimiter=",",
    dtype=None,
    encoding="utf-8"
)

print(iris[:5])

[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa')]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [143]:
# Write your code here:
species = iris['f4']
print(species[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [144]:
# Write your code here:
iris_2d = np.array([
    iris['f0'],
    iris['f1'],
    iris['f2'],
    iris['f3']
]).T

print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [145]:
# Write your code here:
sepal_length = iris_2d[:, 0]
mean = np.mean(sepal_length)
print(mean)
median = np.median(sepal_length)
print(median)
std_deviation = np.std(sepal_length)
print(std_deviation)

5.843333333333334
5.8
0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [146]:
# Write your code here:
normalized = (sepal_length - np.min(sepal_length)) / (np.max(sepal_length) - np.min(sepal_length))
print(normalized[: 5])
print(np.max(normalized))
print(np.min(normalized))

[0.222 0.167 0.111 0.083 0.194]
1.0
0.0


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [147]:
# Write your code here:
softmax_score = np.exp(sepal_length) / np.sum(np.exp(sepal_length))
print(softmax_score[: 5])
print(np.sum(softmax_score))

[0.002 0.002 0.001 0.001 0.002]
0.9999999999999999


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [148]:
# Write your code here:
print(np.percentile(sepal_length,5))
print(np.percentile(sepal_length,95))

4.6
7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [149]:
# Write your code here:
indices = np.random.choice(iris_2d.size,20,replace=False)

iris_2d.ravel()[indices] = np.nan

### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [150]:
# Write your code here:
print(np.isnan(iris_2d).sum())

0


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [151]:
# Write your code here:


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [152]:
# Write your code here:


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [153]:
# Write your code here:


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [154]:
# Write your code here:


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [155]:
# Write your code here:


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [156]:
# Write your code here:


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [157]:
# Write your code here:


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [158]:
# Write your code here:


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [159]:
# Write your code here:


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [160]:
# Write your code here:


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [161]:
# Write your code here:


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [162]:
# Write your code here:


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [163]:
# Write your code here:


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [164]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [165]:
# Write your code here:
a = np.clip(a,10,30)
print(a)

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [166]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [167]:
# Write your code here:


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [168]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [169]:
# Write your code here:


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [170]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [171]:
# Write your code here:


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.